# Configuración de driver y navegador
# WebDriver configuracion
webdriver.driver=chrome
webdriver.autodownload=true

# Chrome options
chrome.switches=--start-maximized;\
  --disable-notifications;\
  --disable-popup-blocking;\
  --remote-allow-origins=*;\
  --disable-extensions

# Configuración de tiempos de espera
webdriver.timeouts.implicitlywait=10000
webdriver.wait.for.timeout=15000

# Serenity report configuration
serenity.report.encoding=UTF-8
serenity.take.screenshots=FOR_FAILURES
serenity.reports.show.step.details=true

# Base URL
webdriver.base.url=https://www.saucedemo.com

# Cucumber report options
serenity.cucumber.tag.separator=,